import { Roboto } from "next/font/google";
import "./globals.css";

import AppProvider from "./components/AppContext"
import { Toaster } from "react-hot-toast";
import Footer from "@/app/components/FooterComponent/Footer";



const roboto = Roboto({ subsets: ["latin"] ,weight: ['400','500','700'] });

export const metadata = {
  title: "ST PIZZA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>

        <main className="  " >
          <AppProvider>
            <Toaster/>
    
        {children}

          <Footer/>
          </AppProvider>
        </main>
        </body>
    </html>
  );
}
